class Iron{
    constructor(x,y,w,h){
        this.w=120
        this.h=50
    this.body=Matter.Bodies.rectangle(x,y,this.w,this.h,{
        density:50,
        friction:50,
        restitution:0
       })
    Matter.World.add(myworld,this.body)
    this.img=loadImage("stone.png")
    }
    display(){
    push()
    imageMode(CENTER) 
    translate(this.body.position.x,this.body.position.y)
    rotate(this.body.angle)
    image(this.img,0,0,this.w,this.h) 
    pop()
    }
    }