class Rubber{
    constructor(x,y,w,h){
        this.w=100
        this.h=100
    this.body=Matter.Bodies.rectangle(x,y,this.w,this.h,{
        density:1,
        friction:5,
        restitution:0.3 
       })
    Matter.World.add(myworld,this.body)
    this.img=loadImage("b.png")
    }
    display(){
    push()
    imageMode(CENTER) 
    translate(this.body.position.x,this.body.position.y)
    rotate(this.body.angle)
    image(this.img,0,0,this.w,this.h) 
    pop()
    }
    }